import type { Metadata } from "next";
import { Inter, Mulish } from "next/font/google";
import "./globals.css";
import { Satisfy, Lora } from "next/font/google"

const inter = Inter({ subsets: ["latin"] });

//👇 Configure our font object
const mulish = Mulish({
  subsets: ['latin'],
})

const stylish = Satisfy({
  subsets: ['latin'],
  weight: "400",
})

const lora = Lora({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>{children}</body>
    </html>
  );
}
